module.exports = { monsters: [
    {   name:'Rabbit',
        class:'Beast',
        temperament:'Timid',
        huntReward:'Rabbit-Leg',
        captureReward:'Rabbit',
        huntCashReward:20,
    },
    {   name:'Boar',
        class:'Beast',
        temperament:'Aggressive',
        huntReward:'Boars-Head',
        captureReward:'Boar',
        huntCashReward:40,
    },
    {   name:'Elephant',
        class:'Beast',
        temperament:'Terrortorial',
        huntReward:'Elephant-Tusks',
        captureReward:'Elephant',
        huntCashReward:80,
    },
    {   name:'Imp',
        class:'Demon',
        temperament:'Timid',
        huntReward:'Imp-Staff',
        captureReward:'Imp',
        huntCashReward:30,
    },
    {   name:'Lava-Worm',
        class:'Demon',
        temperament:'Feral',
        huntReward:'Lava-Worm-Eyes',
        captureReward:'Lava-Worm',
        huntCashReward:60,
    },
    {   name:'Hell-Wraith',
        class:'Demon',
        temperament:'Scourge',
        huntReward:'Lost-Souls',
        captureReward:'Hell-Wraith',
        huntCashReward:120,
    },
    {   name:'Skeleton',
        class:'Undead',
        temperament:'Mindless',
        huntReward:'Bones',
        captureReward:'Skeleton',
        huntCashReward:40,
    },
    {   name:'Zombie',
        class:'Undead',
        temperament:'Highly Aggressive',
        huntReward:'Undead-Brain',
        captureReward:'Zombie',
        huntCashReward:80,
    },
    {   name:'Necromancer',
        class:'Undead',
        temperament:'Studios',
        huntReward:'Necronomicon',
        captureReward:'Necromancer',
        huntCashReward:160,
    }
]};
